namespace Runtime {
    enum PartId {
        Unknown,
        CartridgeSlot,
        EjectButton,
        EjectFlap,
        EjectMechanism,
        Heatsink,
        HullBottom,
        HullTop,
        Mainboard,
        MainboardShield,
        PowerLED,
        PowerSwitch,
        PowerSwitchMechanism,
        PowerSwitchMechanismSwitchAndCable,
        PowerSwitchMechanismSwitch,
        ResetButton,
        LEDGlass,
        LEDDiode,
        CartridgeFlap,
        ChipCPU,
        ChipRCP,
        ChipRDRAM,
        ControllerSockets,
        Cartridge,
    }
}
